import {StyleSheet} from 'react-native'

const styles = StyleSheet.create({
    profileRowContainer:{
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        width:'100%',
        justifyContent:'space-between',
        paddingVertical:5,
        paddingRight:10,
        borderBottomEndRadius:10,
        borderBottomStartRadius:10,
        elevation:10,
        backgroundColor:'#E9E6F2'
    },
    textWelcome:{
        fontSize:18,
        marginLeft:-12
    },
    profileContainer:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'flex-end',
    },
    greeting:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'flex-start',
    },
    profileImage:{
        width:36,
        borderRadius:25,
        aspectRatio:1,
        marginRight:5,
        
    },
    logoImage : {
        width:72,
        aspectRatio:1,
        borderRadius:25,
    },
    dailyWordContainer:{
        backgroundColor:'#F3D6E4',
        padding:20,
        borderRadius:25,
        borderWidth:1,
        borderColor:'#eee',
        elevation:10,
        marginHorizontal:10,
        marginVertical:15

    },
    dailyWordRow:{
        flexDirection:'row',
        alignItems:'center'
    },
    dailyWordButtons:{
        flexDirection:'row',
        marginLeft:'auto'
    },
    dailyWordTitle:{
        color:'#8E4A7C',
        fontSize:23,
        fontWeight:'900'
    },
    dailyWordLabel:{
        fontSize:12,
        fontStyle:'italic',
        color:'gray',
        marginTop:10
    },
    dailyWordContent:{
        fontSize:15,
        fontWeight:'700'
    },
    statRow:{
        flexDirection:'row',
        justifyContent:'space-around',
        alignItems:'center',
        paddingHorizontal:15,
        gap:10,
        marginTop:5
    },
    statItemButton:{
        borderRadius:25,
        borderWidth:1,
        borderColor:'#E6E1F0',
        paddingVertical:10,
        paddingHorizontal:20,
        backgroundColor:'white',
        flex:1,
        height:70,
        elevation:5
    },
    statItemRow:{
        flexDirection:'row',
        alignItems:'center'
    },
    statColumn:{
        alignItems:'center'
    },
    quickMenu:{
        padding:20
    },
    quickMenuColumn:{
        alignItems:'center',
        flex:1,
        backgroundColor:'white',
        marginRight:10,
        paddingHorizontal:10,
        paddingVertical:10,
        width:100,
        borderRadius:15,
        borderColor:'#E8E4F2',
        borderWidth:1,
        backgroundColor:'#E9E6F2'
        
    },
    scrollView:{
        display:'flex',
        flexDirection:'row'
    },
    recentWord:{
        flexDirection:'row',
        justifyContent:'space-around',
        paddingVertical:10,
        paddingHorizontal:20,
        backgroundColor:'white',
        borderRadius:15,
        marginBottom:10
    }
})

export default styles;