import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    headerTopRow:{
        flexDirection:'row',
        justifyContent:'space-between',
        width:'100%',
        alignItems:'center',
        marginBottom:20
    },
    headerRowButtons:{
        padding:5,
        aspectRatio:1,
        backgroundColor:'white',
        borderRadius:10,
        justifyContent:'center',
        alignItems:'center'
    },
    subscriptionArea:{
        paddingVertical:5,
        paddingHorizontal:10,
        borderRadius:15,
        borderWidth:1,
        borderColor:'#8B5CF6',
        flexDirection:'row',
        backgroundColor:'white'
    },
    profilePhoto:{
        width:120,
        height:120,
        borderRadius:10,
        marginBottom:10
    },
    statColumn:{
        flex:1,
        alignItems:'center',
        gap:5
    },
    inviteButton:{
        flexDirection:'row',
        alignItems:'center',
        borderRadius:15,
        borderWidth:1,
        borderColor:'#8DB580',
        backgroundColor:'#E9F5DB',
        width:'100%',
        paddingVertical:7,
        marginBottom:20
    },
    consoleButton:{
        flexDirection:'row',
        alignItems:'center',
        borderRadius:15,

        width:'100%',
        paddingVertical:7,
        marginBottom:10
    },
    edipPhoto:{
        marginTop:'auto',
        marginBottom:10,
        backgroundColor:'#8e4a7c',
        padding:5,
        borderRadius:13,
        marginLeft:-35
    },
    profileDetailContainer:{
        width:'90%',
        backgroundColor:'white',
        borderRadius:10,
        marginTop:10
    },
    profileDetailItem:{
        flexDirection:'row',
        paddingHorizontal:10,
        paddingVertical:12,
        alignItems:'center'
    },
    profileLabel:{
        color:'#64748B'
    },
    profileValue:{
        color:'#8e4a7c',
        marginLeft:'auto',
        fontWeight:'500'
    },
    changePasswordButton:{
        backgroundColor:'#8e4a7c',
        marginLeft:'auto',
        padding:5,
        borderRadius:5
    },
    deleteAccountButton:{
        marginTop:'auto',
        marginBottom:30,
        borderWidth:1,
        borderColor:'red',
        width:'90%',
        borderRadius:15,
        paddingVertical:10,
    },
    preferenceCategory:{
        backgroundColor:'#e1bee7',
        borderWidth:1,
        borderColor:'white',
        paddingVertical:10,
        borderRadius:15,
        paddingHorizontal:8,
        marginBottom:10,
        elevation:5
    }

});

export default styles;