import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: '#F5F3FF',
        paddingHorizontal: 20,
    },
    questionArea: {
        backgroundColor: '#FFFFFF',
        width: '100%',
        paddingVertical: 36,
        paddingHorizontal: 20,
        marginTop: 16,
        marginBottom: 32,
        borderRadius: 24,
        borderWidth: 1.5,
        borderColor: '#E9E3FF',
        shadowColor: '#5B3FD3',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    question: {
        color: '#1F2937',
        fontSize: 24,
        fontWeight: '800',
        textAlign: 'center',
        letterSpacing: 0.5,
    },
    lettersArea: {
        flexDirection: 'row',
        gap: 8,
        justifyContent: 'center',
        alignItems: 'center',
        flexWrap: 'wrap',
        paddingHorizontal: 4,
        marginBottom: 20,
    },
    letterInputContainer: {
        aspectRatio: 1,
        width: 48,
        minHeight: 48,
        justifyContent: 'center',
        alignItems: 'center',
    },
    letterInput: {
        flex: 1,
        width: '100%',
        textAlign: 'center',
        fontSize: 22,
        textAlignVertical: 'center',
        fontWeight: '800',
        backgroundColor: '#FFFFFF',
        borderRadius: 14,
        borderColor: '#DDD6FE',
        borderWidth: 2,
        color: '#1F2937',
        shadowColor: '#5B3FD3',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 4,
        elevation: 2,
    },
    letterInputCorrect: {
        backgroundColor: '#DCFCE7',
        borderColor: '#22C55E',
        color: '#15803D',
    },
    letterInputWrong: {
        backgroundColor: '#FEE2E2',
        borderColor: '#EF4444',
        color: '#B91C1C',
    },
});

export default styles;